### ISSUE TITLE
Api Requests 400 with bad Authorization

### ISSUE THREAD

**Issue by Austinb** [austinkregel/tamber-php-sdk#1]
I am not sure if this ever worked or if Tamber changed their api but the InteractsWithApi::sendRequest() does not work without adding a trailing ':' to the Basic Auth header.

```
Client error: `POST https://api.tamber.com/v1/event/track` resulted in a `400 Bad Request` response: {"error":"Authorization failed, check to make sure that you set your project/engine keys with correct Basic Auth syntax. 
```

Changing to add the trailing ':' makes it work as expected. 

```php
'Authorization' => 'Basic ' . base64_encode(Tamber::getApiToken().':'),
```

**Comment by Austinb** [comment]
As an aside you may want to think about adding the "Engine Key" as a setting in the class and adding support for that into the request side.  Most of the API calls do not require it to be there.  See: https://tamber.com/docs/api/#authentication

**Comment by austinkregel** [comment]
Hey @Austinb !
To be totally honest I started this and had intentions to use it but my job and my side projects led me elsewhere. 

If you're willing to do so, I'll be happy to review some PRs to get everything up-to-date!

**Comment by austinkregel** [comment]
I also imagine that Tamber has done some API upgrades and breaking changes since I first created this package

**Comment by austinkregel** [comment]
Just wanted to let you know that there's finally a release `v0.0.1` and I think I've addressed the issues you were talking about. 

I also took the liberty of including your suggestion in here and adding support for the engine key :smile: 

If you find more issues in your use please let me know! 😃
