### ISSUE TITLE
ext-json doesnt match php version

### ISSUE THREAD

**Issue by Austinb** [austinkregel/tamber-php-sdk#4]
In the composer.json you have `ext-json` set to version 1.6 or greater which is PHP 7.1 I believe but you have minimum version of PHP set to 5.6.  The ext-json does not allow install in composer for php versions 5.6 and 7.0 without using the `--ignore-platform-reqs` option.  Currently have a project using 7.0 which is json version 1.4 and cant install this library the normal way. 

Unless you are using specific new constants or changes in the JSON extension available in PHP 7.1+ (https://www.php.net/manual/en/function.json-decode.php) the value in composer.json should be `"ext-json": "*"` or change your minimum version of PHP to match the version of `ext-json` you have defined.

Thanks for all the work!

**Comment by austinkregel** [comment]
@Austinb just updated this for ya, and I marked a major release as well for the change, nothing else changes in the release and nothing will break between the last release and this release. 🙌 

Thank you for pointing out this issue!
